WHENEVER SQLERROR EXIT 1;
WHENEVER OSERROR EXIT 2;
SET LINESIZE 100;
SET PAGESIZE 0;
SET FEEDBACK OFF;
SET VERIFY OFF;
SET DOC OFF;
SET ECHO OFF;
SET TRIMSPOOL ON;
SET TRIMS ON;
SET TERM OFF;
SET HEADING OFF;
SET COLSEP '|';

SPOOL &1;

SELECT NOMBRE_PROCESO
FROM MTDT_PROCESO PROCESO
WHERE PROCESO.ID_BLOQUE ='#VAR_BLOQUE#'
AND ESTADO = 'A'
ORDER BY PROCESO.CVE_PROCESO;



SPOOL OFF;
EXIT;

